language: node_js
node_js:
- '13'
script:
- npm run test
- npm run build
deploy:
- provider: releases
  api_key:
    secure: "wUuJZGJthJL1cCMQ0rijV/8CDmCL+PAycB2YQnkrdzKiCWkZHblyRf0tJJe9KohXAz+ANiomZ/AGNncE+s5qE7Fo2RB/XbLtpNAjU6akftAuBActhHgAWW6VwasQm95DELMztMhHveNP5oxI/pWQX0cwEhZDmlV7WZOQAVlCb9PBVV9kY5g2HQN0dL48295r+GKvPM4vYZi6pLJ+0Jw6XssIexKgeLKnpWS/FMjbkzRkeI57uJNHA6a/Opte4KZE8D3Rd3OFieJn3JllFfdkCObvt0K7ztZqQhn71p3WDVAY+CJDLx4+MUUqTP2epc2xVZ12Rl7AsoU0EQqYYjJpskTlmQEthdHPfKUnT2J2C6jwAz7EUECWoLO59cvusngvFbiLDMHQn31C4nZyfI2dsLr4EXv7ZH24vpeT3W9Uiu22vZZwidxTAa4yeRjAdX9ephvJYbQh6PK1+Ngpo7dr74sU/zXjrvYG9j72lGeVqXYspqK9BtUvDt7j4nZMXNB/zpBl8CYQDLiajP/KPard0DrWJ0hSu54VY/I/37JEfX8eS0NL1H1feuZFzBtkeBJtdB9KVBvkEUkNWRrfmdoldXYhxlCVp9CecF463YJvssbpeXWhobx5e6pexfBuLZmcRBkoHMiPTWe0SVQj90sb8bqsj0kW3VYMCi/VSSytojM="
  file: dist/TypetalkEmoreact.user.js
  on:
    repo: mohno007/typetalk-emoreact
    tags: true
  skip_cleanup: 'true'
- provider: pages
  github-token:
    secure: "T5+wP8HayDCg6HtM6X1nefekUl1jMG1o+WOGnnbqHqOiugAate5lfI9hGVJNhZyxGVtQC5sff/ajK1WeGt9ko5XgnghyWCKFx4UINi1xiZzSaQ3CBTzkmggmHzDys7foG/Cla5Y67j4dCYtzt8/YJJnPvLQKW/mjnAVipdc5i+5KlLz6WKF1dE0rw3NigEz24ECiJi+GzwSrFFGiCsvCyVY22U1h6Lofavb/RkM82qeZqZqLuAYKIZKZKcGYqtl/sQa9HLtCJv7KXfrNOmYB28/u4lVPtNBfQscoVxXCHRnatyyb4RqtM1MhJkJWipDY1Zy0vM2XwwY+l+wB956L61BN2DDe5OGFjhdPEaUGm0cC2j6zPLvRh7on6HT5T6Nuo13mIctD4nYz/kkPQjHJPzF6dIfpSj0QwRuIy/EN7WQ2gBlqz6GU7ermzAMlT6Zy5Wy0EcHj7qjPghM08+y9PbZvB7P6RDsesV1MIoDCkJ3wpJ5ZAiFU9DBdoGGfVnpzO9GQOdUxx4l9G3jbpEU9aSFC0JJUbz6ZvStM/kCiTvLAwClC2kYqNOmsAUal1Y4iEbtohqBvp3pB8r0akm6u5lSwGIjg8G+/rQ2//tYonbqJh3va2hfbsM28hSUsek7pkBznIFtpIHYY++fbM6KNwtSgrR1T6bXbXwaET9Vie8o="
  keep-history: true
  skip-cleanup: true
  local-dir: dist/
  on:
    tags: true
